server:
    port: 8080
    servlet:
        contextPath: /identity
spring:
    application:
        name: identity-service
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/identity}
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
jwt:
    signerKey: "262b41abac6b3821a8b7397b4f81bc4d11065ac582940d601533eceee45dd7c8"