server:
    port: 8080
    servlet:
        contextPath: /identity
spring:
    application:
        name: identiy-service
    datasource:
        url: jdbc:mysql://localhost:3306/identity
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
jwt:
    signerKey: "262b41abac6b3821a8b7397b4f81bc4d11065ac582940d601533eceee45dd7c8"